### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jrdalenberg**
This updates all dependencies to latest versions as of February 8th, 2023.

### CODE REVIEW

**Comment by SiggiSmara** [comment]
Thanks @jrdalenberg! Just tested your updated version.  Runs great.

**Comment by jrdalenberg** [comment]
@SiggiSmara thanks for testing!

**Comment by khicks** [comment]
@jrdalenberg Thanks for this! Everything still seems to run great. Always disheartening when the tutorial breaks after you do exactly what it says.

**Comment by mjhea0** [comment]
Thanks for the PR, @jrdalenberg. Since the code is tied to a tutorial, they both need to be updated at the same time. Doing that now in https://github.com/testdrivenio/fastapi-celery/pull/13.

**Pull request closed without merging**
